### PR TITLE
[ADDED] TLSHandshakeFirst option

### PR DESCRIPTION
**Pull request by kozlovic**
This allows to connect to a server that is also configured to perform the TLS handshake first, that is, before sending the INFO protocol.

Signed-off-by: Ivan Kozlovic <ivan@synadia.com>

### CODE REVIEW

**Review by derekcollison — APPROVED** [review]
LGTM

**Review by piotrpio — APPROVED** [review]
Looks good, but I think we should wait with merging it until this feature is introduced in the server right?

**Comment by kozlovic** [comment]
> I think we should wait with merging it until this feature is introduced in the server right?

@piotrpio Actually no. The server relies on the client new API for its tests. I made the client not depend on the server for the test (since it is quite simple here), but not the server. If you merge and soon after have to do a release while the server still does not have the feature, then it would have to be stated in the client's release notes that this option is to be used with servers at version x.y.z and above.

**Comment by piotrpio** [comment]
@kozlovic Got it - in that case, I'm merging the PR

**Pull request merged**
