### PR TITLE
Add new client inboxes.

### PR DESCRIPTION
**Pull request by bfoxstudio**
New clients inboxes.  Necessary changes to integrate access control in NATS streaming
In new version use clients section in config for automatically allow subscribe and publish to "_INBOX._CLIENTS.ClientIdXYZ.>". Not use "_INBOX.>" publish and subscribe with clients. "_INBOX.>" will be allowed to write and read other _INBOX._CLIENTS.

### CODE REVIEW

**Comment by bfoxstudio** [comment]
> I think I would prefer to make the appropriate changes at the STAN level to enable more fine grain authorization control rather than here.

I implemented authorization level in stan client stan server and gnats.  In stan response authorization use inboxes. 
For full sendbox it is necessary to split client inboxes.
Review on other repositories in progress.

Have any suggestions?

**Comment by derekcollison** [comment]
We have this on our list to review. Will circle back when we have some time to look more closely at a solution for the STAN server and all STAN clients etc.

**Comment by kozlovic** [comment]
@bfoxstudio I understand why you tried to do that to solve the auth/perm issues with NATS Streaming, but as @derekcollison mentioned, I don't think this is the right approach. We would still need the NATS Streaming Go client to be modified to use those new APIs along with all other client libraries that support streaming.
I think that the solution will need to be implemented at the level of the NATS Streaming Server in some fashion.

**Comment by bfoxstudio** [comment]
I will post a solution soon to nats streaming, but without inbox for clientId we need open all inboxes for all users. Or we need change logic in streaming for stop use _INBOX.
i create request to gnats in my fork: https://github.com/bfoxstudio/gnatsd/pull/1
go-nats-streaming in my fork https://github.com/bfoxstudio/go-nats-streaming/pull/1/files (beta code)
nats-streaming-server in my fork https://github.com/nats-io/nats-streaming-server/pull/758/files (beta code)
In my code req123 - client, foo123 - channel. Permissions work. I think to modify the configuration by automatically adding the correct subscriptions for streaming
					```
Publish: &server.SubjectPermission{Allow: []string{
						"_STAN.discover.*.req123",
						"_STAN.close.*.req123",
			
						"_STAN.pub.*.foo123",
			
						"_STAN.sub.*.foo123",
						"_STAN.unsub.*.foo123",
						"_STAN.subclose.*.foo123"}},
					Subscribe: &server.SubjectPermission{Allow: []string{
						"_STAN.acks.req123.>"}},
```

**if the concept is wrong**. Suggest what changes to make in the streaming.

**Comment by kozlovic** [comment]
Closing since PR #767 has been merged.

**Pull request closed without merging**
