### PR TITLE
[IMPROVED] Add extra option to OrderedConsumerConfig

### PR DESCRIPTION
**Pull request by mwain**
Id like to set these options for ordered consumers.

### CODE REVIEW

**Comment by piotrpio** [comment]
Hello @mwain, thank you for the contribution! While I agree that metadata may be useful for ordered consumers, I'm not sure about  `MaxRequestMaxBytes` - max bytes buffered client side can be set using options on `Consume` and `Messages` - what's your use case here?

**Comment by mwain** [comment]
Hi @piotrpio, thanks for the review. We used it to cap the bytes being buffered. TBH i didn't see the `PullMaxBytes` option 🙈 

Would you like me to update this to remove `MaxRequestMaxBytes`?

**Comment by piotrpio** [comment]
@mwain That would be great, thanks!

**Comment by mwain** [comment]
@piotrpio Updated

**Review by piotrpio — APPROVED** [review]
LGTM, Thank you for the contribution!

**Pull request merged**
