### PR TITLE
support setting a reply subject when publishing messages

### PR DESCRIPTION
**Pull request by ripienaar**

### CODE REVIEW

**Comment by ripienaar** [comment]
nats-req doesn't support listening for more than 1 reply.  I wanted a easy way to test js next with a batch of 10.  But in general being able to publish with this set is useful in case the listener is a different process

**Comment by derekcollison** [comment]
Should we add optional way for nats-req to wait for more responses?

**Comment by ripienaar** [comment]
Yeah I want to do that too - I dont think Request() support that so would need to set up a inbox and all sorts, but yeh i want to do that

**Comment by derekcollison** [comment]
But you still want option for reply for nats-pub yes?

I would probably keep nc.Publish() and add conditional if reply != "" use nc.PublishReply().

**Comment by ripienaar** [comment]
Yeah as a general toy to play with patterns its nice to be able to put arbitrary replies :) Ok - How'd I miss`PublishReply` :P will rework

**Comment by derekcollison** [comment]
No worries.

**Comment by ripienaar** [comment]
Updated and updated for latest staticcheck, remaining issues not related to this PR

**Pull request merged**
