### PR TITLE
[FIXED] Closing connection on max subscriptions exceeded

### PR DESCRIPTION
**Pull request by piotrpio**
Signed-off-by: Piotr Piotrowski [piotr@synadia.com](mailto:piotr@synadia.com)

### CODE REVIEW

**Comment by wallyqs** [comment]
any other side effect from the changes? seems this also now avoids closing when creating an invalid subscription?

**Comment by derekcollison** [comment]
Just checking, when we get this error we should not be closing the connection from the client side.

**Comment by piotrpio** [comment]
@derekcollison correct, this used to be the case but this change will cause it to just invoke error callback.

**Review by wallyqs — APPROVED** [review]
LGTM

**Comment by fmontorsi-equinix** [comment]
hey @piotrpio ,
I actually stumbled on this PR and I wonder if this might fix the behavior I described at https://github.com/nats-io/nats-server/discussions/5994 . In particular I'm trying to understand why my consumers are stopping processing shortly after receiving the "nats: Exceeded MaxWaiting" error... 
Do you think this PR would restore processing in the consumers that received that "nats: Exceeded MaxWaiting" error? 
thanks

**Comment by Jarema** [comment]
This one is about subscriptions, not max_waiting in pull requests, so I doubt its related.

**Review by Jarema — APPROVED** [review]
LGTM

**Pull request merged**
