### PR TITLE
Bump NATS Server version from the server in go_test.mod

### PR DESCRIPTION
**Pull request by shayyxi**
https://github.com/nats-io/kubecon-contribfest/issues/9

### CODE REVIEW

**Comment by shayyxi** [comment]
I would work on checking the flaky tests.

**Comment by shayyxi** [comment]
I would continue the work on flaky tests after kubecon for sure.

**Comment by piotrpio** [comment]
@shayyxi yeah, that continues to be a problem. With this PR one test seems to be testing pretty consistently (`TestNoRaceObjectContextOpt`) - I'm investigating whether bumping the server version may have something to do with it.

**Review by piotrpio — APPROVED** [review]
LGTM

I'm merging the PR (the changes are good), I'll continue investigating the flappers

**Pull request merged**
