### PR TITLE
[CHANGED] More verbose endpoint info on INFO requests

### PR DESCRIPTION
**Pull request by piotrpio**
Addresses https://github.com/nats-io/nats-architecture-and-design/issues/220

### CODE REVIEW

**Review by Jarema — APPROVED** [review]
LGTM

**Review by aricart — COMMENTED** [review]
LGTM

**Comment by oderwat** [comment]
@piotrpio This breaks our systems when we update to 'nats-go' 1.27.0 and make the needed changes.

It seems like that "Info()" on the service was changed, but not the much more important '$SRV.INFO' response. The 'nats schema info io.nats.micro.v1.info_response' is still the old version and does not match the structure in nats-go anymore.

We (and, for example, 'nats-cli') uses this for discovery of our services. With me being the person that requested this change, I am a sad panda right now :(

**Comment by piotrpio** [comment]
@oderwat sorry for your trouble, so you're saying that the change works for you now? If not let me know, we'll be working on that!

**Comment by oderwat** [comment]
@piotrpio this stuff works like a charm. I totally forgot that we needed to recompile the services and was puzzled for some minutes :)

P.S.: There is still the problem with https://github.com/nats-io/nats.go/issues/1307#issuecomment-1587655167 and I can't find a reason for that.

**Comment by piotrpio** [comment]
@oderwat Glad it works fine. Regarding #1307 yes, I've seen it and will be looking at this tomorrow, hope that's ok with you

**Comment by oderwat** [comment]
@piotrpio That is fine. I was just using the nighttime for trying some of the new stuff. The new API has time. The changes to micro were more important to me because we are having some parts of our system released in beta some days ago, and I am nervous and want to use the monitoring and continue writing and testing of the deployment daemon, which is based on the discovery through metadata.

**Comment by ripienaar** [comment]
Nats CLI should have latest schemas in main.

**Pull request merged**
