### PR TITLE
Added API stats support to AccountInfo

### PR DESCRIPTION
**Pull request by derekcollison**
Signed-off-by: Derek Collison <derek@nats.io>

### CODE REVIEW

**Comment by derekcollison** [comment]
I noticed the failed test after brining in updated server. Will take a look in a bit to resolve.

**Review by ripienaar — APPROVED** [review]
LGTM after test fix

**Comment by derekcollison** [comment]
ok found the issue, will wait for next server to hit main branch and will pull in from there.

**Comment by derekcollison** [comment]
ok updated with latest server. Tests pass.

**Pull request merged**
