### PR TITLE
adds endpoint metadata to endpoint stats

### PR DESCRIPTION
**Pull request by ripienaar**

### CODE REVIEW

**Comment by ripienaar** [comment]
Implements https://github.com/nats-io/nats-architecture-and-design/pull/207

**Review by piotrpio — APPROVED** [review]
LGTM

**Comment by piotrpio** [comment]
Let's merge it once https://github.com/nats-io/nats-architecture-and-design/pull/207 is merged.

**Comment by ripienaar** [comment]
I merged the ADR

**Pull request merged**
