### PR TITLE
Updates for rename and go.mod support

### PR DESCRIPTION
**Pull request by derekcollison**
Signed-off-by: Derek Collison <derek@nats.io>

### CODE REVIEW

**Comment by kozlovic** [comment]
@derekcollison This is not triggering Travis-ci because of the name change you think? chicken and egg problem?

**Comment by wallyqs** [comment]
Also need to update import in this test: https://github.com/nats-io/nats.go/blob/ad2d0cc1a82bd042861b6a141009545fa2e07c17/test/json_test.go#L21

**Comment by derekcollison** [comment]
Travis is running, not sure what you mean.

**Comment by derekcollison** [comment]
Thanks Wally, will update.

**Comment by derekcollison** [comment]
Updated Travis and Coveralls

**Pull request merged**
